/**
 * @file    driverObjects.js
 *
 * This file is under development. The intent is to provide a
 * better separation of driver core from user configuration. The
 * end goal is to provide a simpler and potentially data-driven
 * design, largely free of the details of the MIDI Remote API.
 *
 * This should be considered advanced development and will
 * change significantly over a relatively short time span.
 *
 * NOTE: IT IS IMPORTANT NOT TO CONFUSE THE MIDI REMOTE API
 * DATA WITH THE THIS FRAMEWORK!
 */



function    Driver( vendor, model, author )
{
    this.driverApi = midiremote_api.makeDeviceDriver( vendor, model, author );

    this.midiInput = this.driverApi.mPorts.makeMidiInput(  );
    this.midiOutput = this.driverApi.mPorts.makeMidiOutput(  );

    const DEBUG_MODE    = 0

    // @ts-ignore
    if( DEBUG_MODE == 1 )
    {
        /**
         * For debugging MIDI traffic. These MIDI ports are created with
         * loopMIDI and configured with MIDI-OX such that the MIDI
         * traffic in both directions can be recorded. This is very
         * helpful is you want to observe MIDI traffic generated by
         * your callbacks.
         */
        this.driverApi.makeDetectionUnit( ).detectPortPair( this.midiInput, this.midiOutput )
            .expectInputNameEquals( 'To-Cubase' )
            .expectOutputNameEquals( 'From-Cubase' )
            .expectSysexIdentityResponse( '002029', '0101', '0000' )
    }
    else
    {
        /**
         * For standard operation of InControl mode on the SL. These are
         * the ports you would connect to in MIDI-OX for the debug
         * sample above.
         */
        this.driverApi.makeDetectionUnit( ).detectPortPair( this.midiInput, this.midiOutput )
            .expectInputNameEquals( 'MIDIIN2 (Novation SL MkIII)' )
            .expectOutputNameEquals( 'MIDIOUT2 (Novation SL MkIII)' )
            .expectSysexIdentityResponse( '002029', '0101', '0000' )
    }

}


/**
 * Create a driver page instance. Currently the page
 * is built with a fixed number of subpage areas and subpages.
 *
 * @todo Configurable number of subpage areas and subpages.
 *
 * @param deviceDriver MIDI Remote API driver instance.
 * @param pageName          Text page name.
 * @param numSubpageAreas   Number of subpage areas to create.
 * @param numSubPages       Number of subpages per subpage area.
 */
function DriverPage( deviceDriver, pageName, numSubpageAreas, numSubPages )
{
    var pageApi         = deviceDriver.mMapping.makePage( pageName );

    this.name           = pageName;
    this.subpageArea    = [ ];

    /**
     * Create a subpage area.
     *
     * @param   subpageAreaName Text name for the subpage.
     */
    function SubPageArea( subpageAreaName )
    {
        var subPageAreaApi  = pageApi.makeSubPageArea( subpageAreaName );
        this.subPage        = [ ];

        /**
         * Create a subpage.
         *
         * @param   subPageName Text name for the subpage.
         */
        function Subpage( subPageName )
        {
            var subPageApi  = subPageAreaApi.makeSubPage( subPageName );

            /**
             * Callback for subpage activated.
             */
            subPageApi.mOnActivate = function( context )
            {
                console.log( 'Subpage ' + subPageName )
            }
            /**
             * Callback for subpage deactivated.
             */
            subPageApi.mOnDeactivate = function( context )
            {
            }
        }

        for( var i = 0; i < numSubPages; ++i )
        {
            this.subPage[ i ] = new Subpage( 'Subpage ' + i.toString(  ) )
        }

    }

    /**
     * Call for page activated.
     */
    pageApi.mOnActivate = function( context )
    {
        console.log( 'Page ' +  pageName )
    }
    /**
     * Call for page deactivated.
     */
    pageApi.mOnDeactivate = function( context )
    {
    }

    for( var i = 0; i < numSubpageAreas; ++i )
    {
        this.subpageArea[ i ] = new SubPageArea( 'SubPageArea ' + i.toString( ) );
    }
}

function Button( deviceDriver, x, y, w, h )
{
    this.buttonApi = deviceDriver.mSurface.makeButton( x, y, w, h );
    //knobs.push( this );

    this.setShapeCircle = function( )
    {
        this.buttonApi.setShapeCircle( );
    }
}

function Knob( deviceDriver, x, y, w, h )
{
    this.knobApi = deviceDriver.mSurface.makeKnob( x, y, w, h )
    //knobs.push( this );

}

function Fader( deviceDriver, x, y, w, h )
{
    this.faderApi = deviceDriver.mSurface.makeFader( x, y, w, h )
    //faders.push( this );

    this.setTypeVertical = function( )
    {
        this.faderApi.setTypeVertical( );
    }
    this.faderApi.mSurfaceValue.mOnTitleChange = function( context, objectTitle, valueTitle )
    {
    }
    this.faderApi.mSurfaceValue.mOnColorChange = function( context, r, g, b, a, IsActive )
    {
    }
    this.faderApi.mSurfaceValue.mOnDisplayValueChange = function( context, value,  units )
    {
    }
    this.faderApi.mSurfaceValue.mOnProcessValueChange = function( context, value )
    {
    }
}

function Label( deviceDriver, x, y, w, h )
{
    this.labelApi = deviceDriver.mSurface.makeLabelField( x, y, w, h )

}


function TriggerPad( deviceDriver, x, y, w, h ) {
    this.triggerPadApi = deviceDriver.mSurface.makeTriggerPad( x, y, w, h )

}

function PianoKeys( deviceDriver, x, y, w, h, first, last )
{
    this.pianoKeysApi = deviceDriver.mSurface.makePianoKeys( x, y, w, h, first, last )
}

function BlindPanel( deviceDriver, x, y, w, h )
{
    this.blindPanelApi = deviceDriver.mSurface.makeBlindPanel( x, y, w, h )
}


function PitchWheel( deviceDriver, x, y, w, h )
{
    this.pitchWheelApi = deviceDriver.mSurface.makePitchBend( x, y, w, h )
}


function ModWheel( deviceDriver, x, y, w, h )
{
    this.modWheelApi = deviceDriver.mSurface.makeModWheel( x, y, w, h )
}


module.exports =
{
    makeDriver:     Driver,
    makeModWheel:   ModWheel,
    makePitchWheel: PitchWheel,
    makeBlindPanel: BlindPanel,
    makePianoKeys:  PianoKeys,
    makeTriggerPad: TriggerPad,
    makeLabel:      Label,
    makeFader:      Fader,
    makeKnob:       Knob,
    makeButton:     Button,
    makePage:       DriverPage,
}
