/**
 * @file    driverObjects.js
 *
 * This file is under development. The intent is to provide a
 * better separation of driver core from user configuration. The
 * end goal is to provide a simpler and potentially data-driven
 * design, largely free of the details of the MIDI Remote API.
 *
 * This should be considered advanced development and will
 * change significantly over a relatively short time span.
 *
 * NOTE: IT IS IMPORTANT NOT TO CONFUSE THE MIDI REMOTE API
 * DATA WITH THE THIS FRAMEWORK!
 */



function    Driver( vendor, model, author )
{
    // Get the MIDI Remote API interfaces. (Required!)
    var midiremote_api = require( 'midiremote_api_v1' )
    this.driverApi = midiremote_api.makeDeviceDriver( vendor, model, author );

    this.midiInput = this.driverApi.mPorts.makeMidiInput(  );
    this.midiOutput = this.driverApi.mPorts.makeMidiOutput(  );

    const DEBUG_MODE    = 0

    // @ts-ignore
    if( DEBUG_MODE == 1 )
    {
        /**
         * For debugging MIDI traffic. These MIDI ports are created with
         * loopMIDI and configured with MIDI-OX such that the MIDI
         * traffic in both directions can be recorded. This is very
         * helpful is you want to observe MIDI traffic generated by
         * your callbacks.
         */
        this.driverApi.makeDetectionUnit( ).detectPortPair( this.midiInput, this.midiOutput )
            .expectInputNameEquals( 'To-Cubase' )
            .expectOutputNameEquals( 'From-Cubase' )
            .expectSysexIdentityResponse( '002029', '0101', '0000' )
    }
    else
    {
        /**
         * For standard operation of InControl mode on the SL. These are
         * the ports you would connect to in MIDI-OX for the debug
         * sample above.
         */
        this.driverApi.makeDetectionUnit( ).detectPortPair( this.midiInput, this.midiOutput )
            .expectInputNameEquals( 'MIDIIN2 (Novation SL MkIII)' )
            .expectOutputNameEquals( 'MIDIOUT2 (Novation SL MkIII)' )
            .expectSysexIdentityResponse( '002029', '0101', '0000' )
    }

}


/**
 * Create a driver page instance. Currently the page
 * is built with a fixed number of subpage areas and subpages.
 *
 * @todo Configurable number of subpage areas and subpages.
 *
 * @param deviceDriver MIDI Remote API driver instance.
 * @param pageName          Text page name.
 */
function DriverPage( deviceDriver, pageName )
{
    this.name           = pageName;
    this.pageApi        = deviceDriver.driverApi.mMapping.makePage( this.name );
    this.subPageArea    = [  ];

    this.bind = function( control, action )
    {
       this.pageApi.makeActionBinding( control.api.mSurfaceValue, action );
    }
}


/**
 * Create a subpage area.
 *
 * @param driverPage        Parent page.
 * @param subPageAreaName   Name of the subpage area.
 * @param numSubPages       Number of subpages to create for
 *                          this area.
 */
function SubPageArea( driverPage, subPageAreaName, numSubPages )
{
    this.name           = subPageAreaName;
    this.subPageAreaApi = driverPage.pageApi.makeSubPageArea( this.name );
}

/**
 * Create the subpages for a subpage area.
 *
 * @param subPageArea
 * @param subPageName
 */
function SubPage( subPageArea, subPageName )
{
    this.name = subPageName;
    this.subPageApi = subPageArea.subPageApi.makeSubPage( this.name );
}


/**
 * Construct a virtual button for the control surface.
 *
 * @param deviceDriver Driver object.
 * @param x
 * @param y
 * @param w
 * @param h
 */
function Button( deviceDriver, x, y, w, h )
{
    this.api = deviceDriver.driverApi.mSurface.makeButton( x, y, w, h );

    //knobs.push( this );

    this.bind = function( midiInput, channel, cc )
    {
        this.api.mSurfaceValue.mMidiBinding.setInputPort( midiInput ).bindToControlChange( channel, cc );
    }
    this.setShapeCircle = function( )
    {
        this.api.setShapeCircle( );
    }
}

/**
 * Construct a virtual knob for the surface.
 *
 * @param deviceDriver Driver object.
 * @param x
 * @param y
 * @param w
 * @param h
 */
function Knob( deviceDriver, x, y, w, h )
{
    this.api = deviceDriver.driverApi.mSurface.makeKnob( x, y, w, h )
}


/**
 * Construct a virtual fader for the surface.
 *
 * @param deviceDriver
 * @param x
 * @param y
 * @param w
 * @param h
 */
function Fader( deviceDriver, x, y, w, h )
{
    this.api = deviceDriver.driverApi.mSurface.makeFader( x, y, w, h )

    this.setTypeVertical = function( )
    {
        this.api.setTypeVertical( );
    }
}


/**
 * Construct a virtual label for the surface.
 *
 * @param deviceDriver
 * @param x
 * @param y
 * @param w
 * @param h
 */
function Label( deviceDriver, x, y, w, h )
{
    this.api = deviceDriver.driverApi.mSurface.makeLabelField( x, y, w, h )

}


/**
 * Construct a virtual trigger pad for the surface.
 *
 * @param deviceDriver
 * @param x
 * @param y
 * @param w
 * @param h
 */
function TriggerPad( deviceDriver, x, y, w, h ) {
    this.api = deviceDriver.driverApi.mSurface.makeTriggerPad( x, y, w, h )

}


/**
 * Construct a virtual piano keyboard (visual only) for the
 * surface.
 *
 * @param deviceDriver
 * @param x
 * @param y
 * @param w
 * @param h
 */
function PianoKeys( deviceDriver, x, y, w, h, first, last )
{
    this.api = deviceDriver.driverApi.mSurface.makePianoKeys( x, y, w, h, first, last )
}


/**
 * Construct a virtual blind panel (visual only) for the
 * surface.
 *
 * @param deviceDriver
 * @param x
 * @param y
 * @param w
 * @param h
 */
function BlindPanel( deviceDriver, x, y, w, h )
{
    this.api = deviceDriver.driverApi.mSurface.makeBlindPanel( x, y, w, h )
}


/**
 * Construct a virtual pitch wheel for the
 * surface.
 *
 * @param deviceDriver
 * @param x
 * @param y
 * @param w
 * @param h
 */
function PitchWheel( deviceDriver, x, y, w, h )

{
    this.api = deviceDriver.driverApi.mSurface.makePitchBend( x, y, w, h )
}


/**
 * Construct a virtual modulation wheel for the
 * surface.
 *
 * @param deviceDriver
 * @param x
 * @param y
 * @param w
 * @param h
 */
function ModWheel( deviceDriver, x, y, w, h )
{
    this.api = deviceDriver.driverApi.mSurface.makeModWheel( x, y, w, h )
}


module.exports =
{
    makeDriver:         Driver,
    makePage:           DriverPage,
    makeSubPageArea:    SubPageArea,
    makeSubPage:        SubPage,

    makeModWheel:       ModWheel,
    makePitchWheel:     PitchWheel,
    makeBlindPanel:     BlindPanel,
    makePianoKeys:      PianoKeys,
    makeTriggerPad:     TriggerPad,
    makeLabel:          Label,
    makeFader:          Fader,
    makeKnob:           Knob,
    makeButton:         Button,
}
